apache:
    build: ./
    ports:
        - 1814:80
    volumes:
        - ./code:/app
    environment:
        - APACHE_SERVER_NAME=md.dev
        - PHP_SHORT_OPEN_TAG=On
        - PHP_ERROR_REPORTING=E_ALL
        - PHP_DISPLAY_ERRORS=On
        - PHP_HTML_ERRORS=On

mysql:
    image: mysql:5.6
    ports:
        - "3333:3306"
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: admin
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin

data:
    image: mysql:5.6
    volumes:
        - /var/lib/mysql
    command: "true"